let MANIFEST=null, allAssets=null, regionCache={}, inspectionData=null, currentDueYear='2026', dueRows=[], duePage=1, assetPage=1;
const $=id=>document.getElementById(id), PAGE_SIZE=5, today=new Date('2026-08-12T00:00:00');
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n||0).toLocaleString('id-ID');
const dateOnly=v=>{if(!v)return '';const m=String(v).match(/(19|20)\d{2}-\d{2}-\d{2}/);return m?new Date(m[0]+'T00:00:00'):null};
const dateFmt=v=>{const d=dateOnly(v);return d?`${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()}`:(v||'-')};
const riskMatrix={5:{A:'Unsatisfactory',B:'Unsatisfactory',C:'Unsatisfactory',D:'Critical',E:'Critical'},4:{A:'Tolerable',B:'Tolerable',C:'Tolerable',D:'Tolerable',E:'Critical'},3:{A:'Acceptable',B:'Acceptable',C:'Tolerable',D:'Tolerable',E:'Critical'},2:{A:'Favourable',B:'Acceptable',C:'Tolerable',D:'Tolerable',E:'Unsatisfactory'},1:{A:'Favourable',B:'Favourable',C:'Tolerable',D:'Tolerable',E:'Tolerable'}};
const colors={Favourable:'#08ad5a',Acceptable:'#86c744',Tolerable:'#ffe000',Unsatisfactory:'#ffab00',Critical:'#f20b13','No AP Detected':'#d7dce1'};
const order=['Favourable','Acceptable','Tolerable','Unsatisfactory','Critical','No AP Detected'];
const category=r=>{const m=String(r||'').toUpperCase().match(/^([1-5])([A-E])$/);return m?(riskMatrix[+m[1]]?.[m[2]]||'No AP Detected'):'No AP Detected'};

async function loadManifest(){const r=await fetch('data/manifest.json',{cache:'no-store'});if(!r.ok)throw Error(`manifest HTTP ${r.status}`);MANIFEST=await r.json();}
async function loadRegion(slug){if(regionCache[slug])return regionCache[slug];const r=await fetch(`data/regions/${encodeURIComponent(slug)}.json`,{cache:'no-store'});if(!r.ok)throw Error(`region HTTP ${r.status}`);const d=await r.json();regionCache[slug]=Array.isArray(d.assets)?d.assets:[];return regionCache[slug]}
async function loadAllAssets(){if(allAssets)return allAssets;const chunks=await Promise.all((MANIFEST.regions||[]).map(r=>loadRegion(r.slug)));allAssets=chunks.flat();return allAssets}
function regionsOptions(sel){return '<option value="">All Wilayah Kerja</option>'+(MANIFEST.regions||[]).map(r=>`<option value="${esc(r.slug)}">${esc(r.name)}</option>`).join('')}
function setupNav(){document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));$('menuToggle').addEventListener('click',()=>document.body.classList.toggle('sidebar-open'));$('themeBtn').addEventListener('click',()=>document.body.classList.toggle('dark'));
  $('roleBtn').addEventListener('click',e=>{e.stopPropagation();$('roleMenu').classList.toggle('open')});document.querySelectorAll('#roleMenu button').forEach(b=>b.addEventListener('click',()=>{$('roleName').textContent=b.dataset.role;$('roleMenu').classList.remove('open')}));document.addEventListener('click',()=>$('roleMenu').classList.remove('open'));
  const file=$('importFile');file?.addEventListener('change',()=>{$('importFileName').textContent=file.files?.[0]?`Selected: ${file.files[0].name}`:''});
}
function showPage(page){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===page));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const labels={dashboard:['Dashboard','Overview'],assets:['Asset Register','Database'],inspection:['Inspection','History'],rbi:['RBI','Assessment'],reports:['Report','Reports'],master:['Data Master','Master Data'],users:['User Management','Users & Roles'],import:['Import Data','Import'],settings:['Settings','Configuration']};const x=labels[page]||['Dashboard',page];$('crumbParent').textContent=x[0];$('crumbCurrent').textContent=x[1];window.scrollTo({top:0,behavior:'smooth'});if(page==='assets')initAssets();if(page==='inspection')initInspection();if(page==='rbi')initRbi();}
function riskCountsFrom(list){const c={};list.forEach(a=>{const r=String(a.risk1AP||a.risk||'').toUpperCase();if(/^[1-5][A-E]$/.test(r))c[r]=(c[r]||0)+1;else c.Unknown=(c.Unknown||0)+1});return c}
function categoryCounts(raw){const c={};order.forEach(k=>c[k]=0);Object.entries(raw||{}).forEach(([r,n])=>c[category(r)]+=Number(n)||0);return c}
function renderMatrix(elId,raw){const el=$(elId), rows=[5,4,3,2,1],cols=['A','B','C','D','E'];el.innerHTML=`<div class="matrix-wrap"><div class="matrix-y">Likelihood</div><div><div class="matrix-grid"><div></div>${cols.map(c=>`<div class="axis">${c}</div>`).join('')}${rows.map(r=>`<div class="axis">${r}</div>${cols.map(c=>{const key=r+c,cat=riskMatrix[r][c],n=raw[key]||0;return `<div class="risk-cell" style="background:${colors[cat]}"><b>${fmt(n)}</b><small>${key}</small></div>`}).join('')}`).join('')}</div><div class="matrix-x">Consequence</div></div></div>`}
function renderSummary(donutId,summaryId,raw,total){const c=categoryCounts(raw);const entries=order.map(k=>({k,v:c[k]})).filter(x=>x.v>0);let start=0;const seg=entries.map(x=>{const end=start+x.v/total*360,s=`${colors[x.k]} ${start}deg ${end}deg`;start=end;return s}).join(',');$(donutId).innerHTML=`<div class="donut" style="background:conic-gradient(${seg||'#d7dce1 0 360deg'})"><div><b>${fmt(total)}</b><span>Total Asset</span></div></div>`;$(summaryId).innerHTML=`<div class="summary"><h4>RBI Risk Summary</h4><div class="summary-head"><span>Kategori</span><span>Jumlah</span><span>Persentase</span></div>${order.map(k=>`<div class="summary-row"><span><i style="background:${colors[k]}"></i>${k}</span><b>${fmt(c[k])}</b><small>${total?((c[k]/total)*100).toFixed(1):'0.0'}%</small></div>`).join('')}</div>`}
function renderRisk(elMatrix,elDonut,elSummary,raw,total){renderMatrix(elMatrix,raw);renderSummary(elDonut,elSummary,raw,total)}
function initDashboardFilters(){['dashRegion','rbiRegion'].forEach(id=>{if($(id))$(id).innerHTML=regionsOptions()});$('dashRegion').addEventListener('change',()=>applyDashboardFilter());$('dashLocation').addEventListener('change',()=>applyDashboardFilter());$('dashSearch').addEventListener('input',()=>applyDashboardFilter());$('dashExport').addEventListener('click',()=>exportCsv('dashboard.csv',dueRows));$('dueSearch').addEventListener('input',renderDueTable);$('dueExport').addEventListener('click',()=>exportCsv(`inspection-due-${currentDueYear}.csv`,dueRows));
  const assetReg=$('assetRegion');assetReg.innerHTML=regionsOptions(assetReg);assetReg.addEventListener('change',()=>loadAssetRegion());$('assetLocation').addEventListener('change',renderAssets);$('assetSearch').addEventListener('input',renderAssets);$('assetExport').addEventListener('click',()=>exportCsv('asset-register.csv',currentAssetFiltered()));
  $('rbiRegion').addEventListener('change',()=>loadRbiRegion());$('rbiLocation').addEventListener('change',()=>loadRbiRegion());$('rbiSearch').addEventListener('input',()=>loadRbiRegion());$('rbiExport').addEventListener('click',()=>exportCsv('rbi-assessment.csv',currentRbiAssets));
}
async function applyDashboardFilter(){const slug=$('dashRegion').value,loc=$('dashLocation').value,q=$('dashSearch').value.trim().toLowerCase();let list=null,raw=MANIFEST.riskCounts,total=MANIFEST.totalAssets,label='All Wilayah Kerja / All Location';if(slug||loc||q){list=slug?await loadRegion(slug):await loadAllAssets();list=list.filter(a=>(!loc||a.area===loc)&&(!q||`${a.tag} ${a.name}`.toLowerCase().includes(q)));raw=riskCountsFrom(list);total=list.length;label='Filtered'}if(slug){const locs=[...new Set((await loadRegion(slug)).map(a=>a.area).filter(Boolean))].sort();$('dashLocation').disabled=false;$('dashLocation').innerHTML='<option value="">All Location</option>'+locs.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}else{$('dashLocation').disabled=true;$('dashLocation').innerHTML='<option value="">All Location</option>'}renderRisk('dashboardMatrix','dashboardDonut','dashboardSummary',raw,total);$('matrixCount').textContent=`${fmt(total)} Asset`;$('diagramCount').textContent=`${fmt(total)} Asset`}

async function buildDueData(){const assets=await loadAllAssets();return assets.filter(a=>a.inspectionDueDate).map(a=>({...a,due:dateOnly(a.inspectionDueDate)})).filter(a=>a.due)}
async function initDue(){if(!dueRows.length){$('dueCards').innerHTML='<div class="due-card loading">Loading...</div>';const data=await buildDueData();const buckets={'Overdue':[],'2026':[],'2027':[],'2028':[],'2029':[],'2030':[],'> 2030':[]};data.forEach(a=>{const y=a.due.getFullYear();if(a.due<today)buckets.Overdue.push(a);else if(y>=2026&&y<=2030)buckets[String(y)].push(a);else if(y>2030)buckets['> 2030'].push(a)});dueRows=buckets;renderDueCards(buckets);currentDueYear='2026';renderDueTable()}}
function renderDueCards(b){$('dueCards').innerHTML=Object.entries(b).map(([k,v])=>`<button class="due-card ${k===currentDueYear?'selected':''}" data-year="${esc(k)}"><b>${k}</b><span>${fmt(v.length)} Asset</span></button>`).join('');document.querySelectorAll('.due-card').forEach(x=>x.addEventListener('click',()=>{currentDueYear=x.dataset.year;document.querySelectorAll('.due-card').forEach(y=>y.classList.toggle('selected',y===x));renderDueTable()}))}
function currentDueList(){return (dueRows[currentDueYear]||[])}
function renderDueTable(){let list=currentDueList();const q=$('dueSearch').value.trim().toLowerCase();if(q)list=list.filter(a=>`${a.tag} ${a.name} ${a.wilayahKerja||''} ${a.area||''}`.toLowerCase().includes(q));$('dueTitle').textContent=`${currentDueYear} Inspection Due`;$('dueCount').textContent=`${fmt(list.length)} Asset`;const start=(duePage-1)*PAGE_SIZE;const rows=list.slice(start,start+PAGE_SIZE);$('dueTable').innerHTML=`<div class="table-scroll"><table><thead><tr><th>No</th><th>Tag Number</th><th>Equipment Name</th><th>Wilayah Kerja</th><th>Location</th><th>Risk 1AP</th><th>Integrity Status</th><th>Last Inspection</th><th>Inspection Due Date</th><th>Action</th></tr></thead><tbody>${rows.map((a,i)=>`<tr><td>${start+i+1}</td><td class="link">${esc(a.tag)}</td><td>${esc(a.name||'-')}</td><td>${esc(a.wilayahKerja||'-')}</td><td>${esc(a.area||'-')}</td><td><span class="risk-tag r-${String(a.risk1AP||'').toLowerCase()}">${esc(a.risk1AP||'-')}</span></td><td><span class="integrity ${String(a.integrityStatus||'').toLowerCase()}">${esc(a.integrityStatus||'-')}</span></td><td>${dateFmt(a.lastInspectionDate)}</td><td>${dateFmt(a.inspectionDueDate)}</td><td><button class="view-btn" title="View">◉</button></td></tr>`).join('')}</tbody></table></div>${pager(list.length,duePage,p=>{duePage=p;renderDueTable()})}`}
function pager(total,page,cb){const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));return `<div class="pager"><span>Showing ${total?((page-1)*PAGE_SIZE+1):0} to ${Math.min(page*PAGE_SIZE,total)} of ${total} entries</span><div>${Array.from({length:Math.min(pages,3)},(_,i)=>`<button class="${page===i+1?'on':''}" data-p="${i+1}">${i+1}</button>`).join('')}${pages>3?'<em>...</em>':''}${pages>3?`<button data-p="${pages}">${pages}</button>`:''}</div></div>`}

let assetList=[];function currentAssetFiltered(){const q=$('assetSearch').value.toLowerCase(),loc=$('assetLocation').value;return assetList.filter(a=>(!loc||a.area===loc)&&(!q||`${a.tag} ${a.name}`.toLowerCase().includes(q)))}
async function initAssets(){if(!assetList.length){$('assetRegion').innerHTML=regionsOptions();$('assetRegion').value='';$('assetTable').innerHTML='<div class="empty">Pilih Wilayah Kerja untuk memuat asset.</div>'}}
async function loadAssetRegion(){const slug=$('assetRegion').value;if(!slug){assetList=[];$('assetLocation').disabled=true;$('assetTable').innerHTML='<div class="empty">Pilih Wilayah Kerja untuk memuat asset.</div>';return}assetList=await loadRegion(slug);const locs=[...new Set(assetList.map(a=>a.area).filter(Boolean))].sort();$('assetLocation').disabled=false;$('assetLocation').innerHTML='<option value="">All Location</option>'+locs.map(x=>`<option>${esc(x)}</option>`).join('');renderAssets()}
function renderAssets(){const list=currentAssetFiltered();$('assetTable').innerHTML=`<div class="table-scroll"><table><thead><tr><th>No</th><th>Tag Number</th><th>Equipment Name</th><th>Object Type</th><th>Location</th><th>Risk 1AP</th><th>Integrity Status</th><th>Remarks</th></tr></thead><tbody>${list.slice(0,50).map((a,i)=>`<tr><td>${i+1}</td><td class="link">${esc(a.tag)}</td><td>${esc(a.name||'-')}</td><td>${esc(a.objectType||'-')}</td><td>${esc(a.area||'-')}</td><td><span class="risk-tag">${esc(a.risk1AP||'-')}</span></td><td><span class="integrity ${String(a.integrityStatus||'').toLowerCase()}">${esc(a.integrityStatus||'-')}</span></td><td>${esc(a.remarks||'-')}</td></tr>`).join('')}</tbody></table></div><div class="pager"><span>${fmt(list.length)} asset</span></div>`}

let currentRbiAssets=[];async function initRbi(){if(!$('rbiRegion').options.length||$('rbiRegion').options.length===1)$('rbiRegion').innerHTML=regionsOptions();if(!currentRbiAssets.length){renderRisk('rbiMatrix','rbiDonut','rbiSummary',MANIFEST.riskCounts,MANIFEST.totalAssets);$('rbiTableCount').textContent=`${fmt(MANIFEST.totalAssets)} Asset`;renderRbiTable(await loadAllAssets())}}
async function loadRbiRegion(){const slug=$('rbiRegion').value;currentRbiAssets=slug?await loadRegion(slug):await loadAllAssets();const locs=[...new Set(currentRbiAssets.map(a=>a.area).filter(Boolean))].sort();$('rbiLocation').disabled=!slug;$('rbiLocation').innerHTML='<option value="">All Location</option>'+locs.map(x=>`<option>${esc(x)}</option>`).join('');const loc=$('rbiLocation').value,q=$('rbiSearch').value.toLowerCase();let list=currentRbiAssets.filter(a=>(!loc||a.area===loc)&&(!q||`${a.tag} ${a.name}`.toLowerCase().includes(q)));renderRisk('rbiMatrix','rbiDonut','rbiSummary',riskCountsFrom(list),list.length);$('rbiMatrixCount').textContent=`${fmt(list.length)} Asset`;$('rbiDiagramCount').textContent=`${fmt(list.length)} Asset`;$('rbiTableCount').textContent=`${fmt(list.length)} Asset`;renderRbiTable(list)}
function renderRbiTable(list){$('rbiTable').innerHTML=`<div class="table-scroll"><table><thead><tr><th>No</th><th>Tag Number</th><th>Equipment Name</th><th>Wilayah Kerja</th><th>Location</th><th>Risk 1AP</th><th>Integrity Status</th><th>Last Inspection</th><th>Inspection Due Date</th></tr></thead><tbody>${list.slice(0,50).map((a,i)=>`<tr><td>${i+1}</td><td class="link">${esc(a.tag)}</td><td>${esc(a.name||'-')}</td><td>${esc(a.wilayahKerja||'-')}</td><td>${esc(a.area||'-')}</td><td><span class="risk-tag">${esc(a.risk1AP||'-')}</span></td><td><span class="integrity ${String(a.integrityStatus||'').toLowerCase()}">${esc(a.integrityStatus||'-')}</span></td><td>${dateFmt(a.lastInspectionDate)}</td><td>${dateFmt(a.inspectionDueDate)}</td></tr>`).join('')}</tbody></table></div>`}

async function initInspection(){if(inspectionData)return;const r=await fetch('data/inspections.json',{cache:'no-store'});inspectionData=await r.json();const years=[...new Set(inspectionData.map(x=>String(x.date||'').slice(0,4)).filter(x=>/^20\d{2}$/.test(x)))].sort().reverse();$('inspectionYear').innerHTML='<option value="">All Years</option>'+years.map(y=>`<option>${y}</option>`).join('');renderInspection()}
function renderInspection(){const y=$('inspectionYear').value,q=$('inspectionSearch').value.toLowerCase();let list=inspectionData.filter(x=>(!y||String(x.date).startsWith(y))&&(!q||String(x.tag).toLowerCase().includes(q)));$('inspectionTable').innerHTML=`<div class="table-scroll"><table><thead><tr><th>No</th><th>Tag Number</th><th>Inspection Date</th><th>Method</th><th>Finding</th><th>Remarks</th></tr></thead><tbody>${list.slice(0,100).map((x,i)=>`<tr><td>${i+1}</td><td class="link">${esc(x.tag)}</td><td>${dateFmt(x.date)}</td><td>${esc(x.method||'-')}</td><td>${esc(x.finding||'-')}</td><td>${esc(x.remarks||'-')}</td></tr>`).join('')}</tbody></table></div><div class="pager"><span>${fmt(list.length)} records</span></div>`}

function exportCsv(name,rows){if(!rows||!rows.length){alert('Tidak ada data untuk diexport.');return}const keys=['tag','name','wilayahKerja','area','risk1AP','integrityStatus','lastInspectionDate','inspectionDueDate'];const csv=[keys.join(','),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replace(/"/g,'""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}

async function boot(){try{await loadManifest();$('totalAssets')?.textContent=fmt(MANIFEST.totalAssets);$('masterRegions')?.textContent=fmt(MANIFEST.regions?.length);$('masterTypes')?.textContent=fmt(Object.keys(MANIFEST.typeCounts||{}).length);$('masterRbi')?.textContent=fmt(MANIFEST.totalRbi);$('reportLink')?.setAttribute('href',CONFIG.reportUrl||'#');renderRisk('dashboardMatrix','dashboardDonut','dashboardSummary',MANIFEST.riskCounts,MANIFEST.totalAssets);$('matrixCount').textContent=`${fmt(MANIFEST.totalAssets)} Asset`;$('diagramCount').textContent=`${fmt(MANIFEST.totalAssets)} Asset`;initDashboardFilters();setupNav();initDue();$('inspectionSearch').addEventListener('input',renderInspection);$('inspectionYear').addEventListener('change',renderInspection)}catch(e){document.querySelector('main').innerHTML=`<div class="panel error">Database belum tersedia: ${esc(e.message)}</div>`}}
window.addEventListener('DOMContentLoaded',boot);