let MANIFEST=null,currentRegion=null,currentRegionAssets=[],inspectionData=null,rbiRendered=false;const PAGE_SIZE=50,$=id=>document.getElementById(id);const today=new Date();today.setHours(0,0,0,0);let currentDue='2026',tablePage=1,tableSize=5;
window.addEventListener('DOMContentLoaded',async()=>{try{const r=await fetch('data/manifest.json',{cache:'no-store'});if(!r.ok)throw new Error(`manifest.json HTTP ${r.status}`);MANIFEST=await r.json();initApp()}catch(e){document.querySelector('main').insertAdjacentHTML('afterbegin',`<div class="panel notice">Database belum tersedia. <small>${esc(e.message)}</small></div>`)}});
function initApp(){brandAndConfig();renderDashboard(MANIFEST);bindNav();fillDashboardFilters();fillRegions();bindLegacy();}
function brandAndConfig(){$('brand').textContent=CONFIG.brand;document.title=CONFIG.title;}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function escAttr(s){return esc(s).replace(/`/g,'&#96;')}
function fmt(n){return Number(n||0).toLocaleString('id-ID')}
const RISK_MATRIX={5:{A:'Unsatisfactory',B:'Unsatisfactory',C:'Unsatisfactory',D:'Critical',E:'Critical'},4:{A:'Tolerable',B:'Tolerable',C:'Tolerable',D:'Tolerable',E:'Critical'},3:{A:'Acceptable',B:'Acceptable',C:'Tolerable',D:'Tolerable',E:'Critical'},2:{A:'Favourable',B:'Acceptable',C:'Tolerable',D:'Tolerable',E:'Unsatisfactory'},1:{A:'Favourable',B:'Favourable',C:'Tolerable',D:'Tolerable',E:'Tolerable'}};
const RISK_COLORS={Favourable:'#00b050',Acceptable:'#92d050',Tolerable:'#fff200',Unsatisfactory:'#ffc000',Critical:'#ff0000','No AP Detected':'#d9dde3'};const RISK_ORDER=['Favourable','Acceptable','Tolerable','Unsatisfactory','Critical','No AP Detected'];
function riskCategory(r){const m=String(r||'').trim().toUpperCase().match(/^([1-5])([A-E])$/);return m?RISK_MATRIX[+m[1]][m[2]]:'No AP Detected'}
function riskCountMap(data){const o={};data.forEach(x=>{const r=String(x.risk1AP||'').trim().toUpperCase();const k=/^[1-5][A-E]$/.test(r)?r:'Unknown';o[k]=(o[k]||0)+1});return o}
function categoryCounts(data){const o={};RISK_ORDER.forEach(k=>o[k]=0);Object.entries(riskCountMap(data)).forEach(([r,n])=>o[riskCategory(r)]+=n);return o}
function filteredManifestData(){return Array.isArray(MANIFEST?.assetSummary)?MANIFEST.assetSummary:[]}
function normalizeAsset(x){return {tag:x.tag||x.tagNo||x.Tag_No||'',name:x.name||x.description||x.equipmentName||x.Description||'',area:x.area||x.location||x.Location||'',wilayah:x.wilayahKerja||x.region||x.Site||'',objectType:x.objectType||x.type||x.Category||'',risk1AP:String(x.risk1AP||x.risk||''),lastInspection:x.lastInspectionDate||x.lastInspection||x.date||'',inspectionDue:x.inspectionDue||x.inspectionDueDate||x.dueDate||'',rli:x.rliMonths??x.rli??null,damageInternal:x.damageMechanismInternal||x.damageInternal||'',damageExternal:x.damageMechanismExternal||x.damageExternal||''}}
function renderDashboard(){const all=filteredManifestData().map(normalizeAsset),data=applyDashboardFilters(all);$('totalAssets').textContent=fmt(data.length);$('totalInspections').textContent=fmt(MANIFEST.totalInspections);$('totalRbi').textContent=fmt(MANIFEST.totalRbi);$('highRisk').textContent=fmt(data.filter(x=>['Unsatisfactory','Critical'].includes(riskCategory(x.risk1AP))).length);$('matrixBadge').textContent=`${fmt(data.length)} asset`;renderMatrix(data);renderDiagram(data);renderDuePlanning(data);renderDueTable(data)}
function renderMatrix(data){const counts=riskCountMap(data),rows=[5,4,3,2,1],cols=['A','B','C','D','E'];$('riskMatrix').innerHTML=`<div class="rbi-matrix"><div></div>${cols.map(c=>`<div class="mh">${c}</div>`).join('')}${rows.map(r=>`<div class="mh">${r}</div>${cols.map(c=>{const code=`${r}${c}`,cat=RISK_MATRIX[r][c];return `<div class="mc" style="background:${RISK_COLORS[cat]}"><b>${fmt(counts[code]||0)}</b><small>${code}</small></div>`}).join('')}`).join('')}<div class="matrix-y">Likelihood</div><div class="matrix-x">Consequence</div></div>`}
function renderDiagram(data){const cats=categoryCounts(data),total=data.length||1;let start=0;const seg=[];RISK_ORDER.forEach(k=>{const p=cats[k]/total*360;seg.push(`${RISK_COLORS[k]} ${start}deg ${start+p}deg`);start+=p});$('riskTotalBadge').textContent=`${fmt(data.length)} asset`;$('riskDiagram').innerHTML=`<div class="risk-diagram"><div class="risk-donut" style="background:conic-gradient(${seg.join(',')})"><div class="risk-donut-center"><b>${fmt(data.length)}</b><span>Total</span></div></div><div class="risk-summary"><h4>RBI Risk Summary</h4>${RISK_ORDER.map(k=>`<div class="legend-row"><span class="dot" style="background:${RISK_COLORS[k]}"></span><span>${k}</span><b>${fmt(cats[k])}</b><small>${(cats[k]/total*100).toFixed(1)}%</small></div>`).join('')}</div></div>`}
function renderDuePlanning(data){const b={Overdue:0,'2026':0,'2027':0,'2028':0,'2029':0,'2030':0,'> 2030':0};data.forEach(x=>{const d=parseDate(x.inspectionDue);if(!d)return;if(d<today)b.Overdue++;else if(d.getFullYear()<=2030)b[String(d.getFullYear())]++;else b['> 2030']++});$('duePlanning').innerHTML=Object.entries(b).map(([k,v])=>`<button class="due-item ${currentDue===k?'selected':''} ${k==='Overdue'?'overdue':''}" data-due="${k}"><strong>${k}</strong><span>${fmt(v)} Asset</span></button>`).join('');$('duePlanning').querySelectorAll('[data-due]').forEach(b=>b.onclick=()=>{currentDue=b.dataset.due;tablePage=1;renderDashboard()})}
function dueMatches(x){const d=parseDate(x.inspectionDue);if(currentDue==='Overdue')return d&&d<today;if(currentDue==='> 2030')return d&&d.getFullYear()>2030;return d&&d>=today&&String(d.getFullYear())===currentDue}
function renderDueTable(data){let rows=data.filter(dueMatches);const q=($('tableSearch')?.value||'').toLowerCase();if(q)rows=rows.filter(x=>`${x.tag} ${x.name} ${x.wilayah} ${x.area} ${x.risk1AP}`.toLowerCase().includes(q));const total=rows.length,pages=Math.max(1,Math.ceil(total/tableSize));tablePage=Math.min(tablePage,pages);const start=(tablePage-1)*tableSize,view=rows.slice(start,start+tableSize);$('tableTitle').textContent=`${currentDue} Inspection Due`;$('tableBadge').textContent=`${fmt(total)} Asset`;$('tableInfo').textContent=total?`Showing ${start+1} to ${Math.min(start+view.length,total)} of ${fmt(total)} entries`:'Showing 0 entries';$('assetRows').innerHTML=view.map((x,i)=>{const st=integrityStatus(x);return `<tr><td>${start+i+1}</td><td><b class="tag-link">${esc(x.tag||'—')}</b></td><td>${esc(x.name||'—')}</td><td>${esc(x.wilayah||'—')}</td><td>${esc(x.area||'—')}</td><td><span class="risk-chip ${riskTone(x.risk1AP)}">${esc(x.risk1AP||'—')}</span></td><td><span class="status-chip ${st[1]}">${st[0]}</span></td><td>${esc(x.lastInspection||'—')}</td><td>${esc(x.inspectionDue||'—')}</td><td><button class="eye-btn">◉</button></td></tr>`}).join('')||`<tr><td colspan="10" class="empty-cell">No assets found for this filter.</td></tr>`;renderPagination(pages)}
function renderPagination(pages){const p=$('pagination');p.innerHTML='';for(let i=1;i<=pages;i++){if(i>5)break;const b=document.createElement('button');b.textContent=i;b.className=i===tablePage?'active':'';b.onclick=()=>{tablePage=i;renderDashboard()};p.appendChild(b)}}
function riskTone(r){const c=riskCategory(r);return c==='Critical'?'critical':c==='Unsatisfactory'?'unsat':c==='Tolerable'?'tolerable':c==='Acceptable'?'acceptable':'favourable'}
function integrityStatus(x){if(x.rli===null||x.rli===undefined||x.rli==='')return ['Good','good'];const n=Number(x.rli);if(n<=0)return ['Fail','fail'];if(n<=6)return ['Poor','poor'];if(n<=18)return ['Fair','fair'];return ['Good','good']}
function parseDate(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d}
function allRegions(){return (MANIFEST.regions||[]).map(r=>({name:r.name,slug:r.slug,count:r.count}))}
function fillDashboardFilters(){const s=$('dashboardRegion');s.innerHTML='<option value="">All Wilayah Kerja</option>'+allRegions().map(r=>`<option value="${escAttr(r.name)}">${esc(r.name)}</option>`).join('');$('dashboardRegion').onchange=()=>{renderDashboard()};$('dashboardLocation').onchange=()=>renderDashboard();$('dashboardSearch').oninput=()=>renderDashboard();$('dashboardReset').onclick=()=>{$('dashboardRegion').value='';$('dashboardLocation').value='';$('dashboardSearch').value='';renderDashboard()};$('tableSearch').oninput=()=>{tablePage=1;renderDashboard()}}
function applyDashboardFilters(data){const rg=$('dashboardRegion')?.value||'',loc=$('dashboardLocation')?.value||'',q=($('dashboardSearch')?.value||'').trim().toLowerCase();return data.filter(x=>(!rg||x.wilayah===rg)&&(!loc||x.area===loc)&&(!q||`${x.tag} ${x.name} ${x.wilayah} ${x.area}`.toLowerCase().includes(q)))}
function fillRegions(){const select=$('regionFilter');if(!select)return;select.innerHTML='<option value="">Pilih Wilayah Kerja</option>'+(MANIFEST.regions||[]).map(r=>`<option value="${escAttr(r.slug)}">${esc(r.name)} (${fmt(r.count)})</option>`).join('');}
async function selectRegion(slug){currentRegion=null;currentRegionAssets=[];if(!slug){$('assetTable').innerHTML='<div class="empty">Pilih Wilayah Kerja untuk memuat asset.</div>';return}const res=await fetch(`data/regions/${encodeURIComponent(slug)}.json`,{cache:'no-store'});const data=await res.json();currentRegion=data.wilayahKerja;currentRegionAssets=(data.assets||[]).map(normalizeAsset);renderAssetTable(currentRegionAssets)}
function renderAssetTable(list){$('assetCount').textContent=`${fmt(list.length)} asset — ${currentRegion||''}`;$('assetTable').innerHTML=`<table class="asset-table"><thead><tr><th>Tag No.</th><th>Deskripsi Peralatan</th><th>Object Type</th><th>Location</th><th>Risk 1AP</th><th>Integrity Status</th><th>Remarks</th></tr></thead><tbody>${list.slice(0,PAGE_SIZE).map(x=>`<tr><td>${esc(x.tag)}</td><td>${esc(x.name)}</td><td>${esc(x.objectType)}</td><td>${esc(x.area)}</td><td>${esc(x.risk1AP||'-')}</td><td>${esc(integrityStatus(x)[0])}</td><td>${esc(x.remarks||'-')}</td></tr>`).join('')}</tbody></table>`}
function bindNav(){document.querySelectorAll('.side-link,.action-btn,.quick-actions button').forEach(btn=>btn.addEventListener('click',()=>openPage(btn.dataset.page)));$('refreshBtn').onclick=()=>location.reload();$('exportDashboardBtn').onclick=exportCsv;$('exportTableBtn').onclick=exportCsv}
function openPage(name){document.querySelectorAll('.side-link').forEach(b=>b.classList.toggle('active',b.dataset.page===name));if(name==='dashboard'){showOnly('dashboard');return}if(name==='assets'){showOnly('genericPage');setGeneric('ASSET REGISTER','Asset Register','Daftar asset dengan filter wilayah, location dan object type.',MANIFEST.totalAssets,'Registered assets','▤');initAssetsModule();return}if(name==='inspection'){showOnly('genericPage');setGeneric('INSPECTION PLANNING','Inspection History','Inspection history dan distribusi tahun inspeksi.',MANIFEST.totalInspections,'Inspection records','◷');if(!inspectionData)loadInspections();return}if(name==='assessment'){showAssessment();return}const meta={risk:['RISK ANALYSIS','Risk Matrix 1AP','Analisis distribusi risiko berdasarkan likelihood dan consequence.',Object.keys(MANIFEST.riskCounts||{}).length,'Risk codes','◈'],damage:['DAMAGE MECHANISM','Potential Damage Mechanisms','Ringkasan damage mechanism internal dan external.',MANIFEST.totalRbi,'RBI assets','⚠'],rli:['RLI MONITORING','Remaining Life Monitoring','Monitoring Remaining Life Indicator dan asset dengan RLI terpendek.',MANIFEST.totalRbi,'RLI / RBI assets','↗'],planning:['INSPECTION PLANNING','Inspection Planning','Prioritas inspeksi berdasarkan inspection due date.',MANIFEST.totalRbi,'Planned assets','□'],sync:['DATA MANAGEMENT','Data Sync','Status sinkronisasi database dari sumber data.',MANIFEST.totalAssets,'Records loaded','↻'],quality:['DATA MANAGEMENT','Data Quality','Pemeriksaan kelengkapan field utama.',MANIFEST.totalAssets,'Records checked','✓'],reports:['REPORTING','Reports','Akses laporan RBI dan dokumen integrity.',1,'Report source','▱'],users:['ADMINISTRATION','Users & Roles','Pengelolaan pengguna dan role aplikasi.',3,'Configured roles','♙'],audit:['ADMINISTRATION','Audit Log','Riwayat aktivitas pengguna pada aplikasi.',0,'Audit events','≡'],settings:['ADMINISTRATION','System Settings','Konfigurasi assessment period, tampilan dan integrasi.',24,'AP months','⚙']}[name]||['MODULE','RBI Module','Modul aplikasi.',0,'Records','◈'];showOnly('genericPage');setGeneric(...meta)}
function showOnly(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$(id).classList.add('active')}
function setGeneric(eyebrow,title,text,metric,metricText,icon){$('crumb').textContent=title;$('genericEyebrow').textContent=eyebrow;$('genericTitle').textContent=title;$('genericText').textContent=text;$('genericMetric').textContent=fmt(metric);$('genericMetricText').textContent=metricText;$('genericIcon').textContent=icon}
function showAssessment(){showOnly('assessmentPage');const mount=$('assessmentMount');mount.innerHTML=`<div class="breadcrumb">Home / RBI / Assessment</div><div class="page-title-row"><div><div class="eyebrow">RBI ASSESSMENT</div><h1>RBI Assessment</h1><p>Penilaian risiko berdasarkan metodologi Risk Based Inspection (RBI).</p></div><button class="action-btn" id="assessmentExport">Export ↓</button></div><div class="assessment-filters"><select id="assessmentRegion"><option value="">All Wilayah Kerja</option></select><select id="assessmentLocation"><option value="">All Location</option></select><input id="assessmentSearch" placeholder="Search Tag No / Equipment Name"></div><div class="risk-grid"><div class="panel matrix-panel"><div class="panel-head"><div><h3>RBI Risk Matrix 1AP</h3><span>Risk 1AP</span></div><span class="badge" id="assessmentBadge">0 asset</span></div><div id="assessmentMatrix"></div></div><div class="panel diagram-panel"><div class="panel-head"><div><h3>Diagram Risiko 1AP</h3><span>RBI Risk Summary</span></div><span class="badge" id="assessmentTotal">0 asset</span></div><div id="assessmentDiagram"></div></div></div><div class="panel due-panel"><div class="panel-head"><div><h3>Inspection Due Planning</h3><span>Perencanaan inspeksi berdasarkan tanggal due</span></div></div><div id="assessmentDue" class="due-grid"></div></div>`;const reg=$('assessmentRegion');reg.innerHTML='<option value="">All Wilayah Kerja</option>'+allRegions().map(r=>`<option value="${escAttr(r.name)}">${esc(r.name)}</option>`).join('');const rerender=()=>{const all=filteredManifestData().map(normalizeAsset),rg=reg.value,loc=$('assessmentLocation').value,q=$('assessmentSearch').value.toLowerCase(),d=all.filter(x=>(!rg||x.wilayah===rg)&&(!loc||x.area===loc)&&(!q||`${x.tag} ${x.name}`.toLowerCase().includes(q)));$('assessmentBadge').textContent=`${fmt(d.length)} asset`;$('assessmentTotal').textContent=`${fmt(d.length)} asset`;$('assessmentMatrix').innerHTML=$('riskMatrix')?document.getElementById('riskMatrix').innerHTML:'';renderAssessmentMatrix(d);renderAssessmentDiagram(d);renderAssessmentDue(d)};reg.onchange=rerender;$('assessmentLocation').onchange=rerender;$('assessmentSearch').oninput=rerender;$('assessmentExport').onclick=exportCsv;rerender()}
function renderAssessmentMatrix(d){const old=$('riskMatrix');if(old){renderMatrix(d);$('assessmentMatrix').innerHTML=$('riskMatrix').innerHTML;old.innerHTML=''}else{$('assessmentMatrix').innerHTML=''}}
function renderAssessmentDiagram(d){const cats=categoryCounts(d),total=d.length||1;let s=0,parts=[];RISK_ORDER.forEach(k=>{const p=cats[k]/total*360;parts.push(`${RISK_COLORS[k]} ${s}deg ${s+p}deg`);s+=p});$('assessmentDiagram').innerHTML=`<div class="risk-diagram"><div class="risk-donut" style="background:conic-gradient(${parts.join(',')})"><div class="risk-donut-center"><b>${fmt(d.length)}</b><span>Total</span></div></div><div class="risk-summary"><h4>RBI Risk Summary</h4>${RISK_ORDER.map(k=>`<div class="legend-row"><span class="dot" style="background:${RISK_COLORS[k]}"></span><span>${k}</span><b>${fmt(cats[k])}</b><small>${(cats[k]/total*100).toFixed(1)}%</small></div>`).join('')}</div></div>`}
function renderAssessmentDue(d){const b={Overdue:0,'2026':0,'2027':0,'2028':0,'2029':0,'2030':0,'> 2030':0};d.forEach(x=>{const dt=parseDate(x.inspectionDue);if(!dt)return;if(dt<today)b.Overdue++;else if(dt.getFullYear()<=2030)b[dt.getFullYear()]++;else b['> 2030']++});$('assessmentDue').innerHTML=Object.entries(b).map(([k,v])=>`<div class="due-item"><strong>${k}</strong><span>${fmt(v)} Asset</span></div>`).join('')}
function exportCsv(){const rows=filteredManifestData().map(normalizeAsset);const csv=[['Tag Number','Equipment Name','Wilayah Kerja','Location','Risk 1AP','Last Inspection','Inspection Due Date'],...rows.map(x=>[x.tag,x.name,x.wilayah,x.area,x.risk1AP,x.lastInspection,x.inspectionDue])].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='RBI_Assessment_Export.csv';a.click();URL.revokeObjectURL(url)}
async function loadInspections(){try{const r=await fetch('data/inspections.json',{cache:'no-store'});if(!r.ok)throw new Error(`inspections.json HTTP ${r.status}`);inspectionData=await r.json();if(typeof window.renderInspectionByYear==='function')window.renderInspectionByYear(inspectionData)}catch(e){console.error(e)}}
function initAssetsModule(){if($('regionFilter'))$('regionFilter').onchange=e=>selectRegion(e.target.value)}
function bindLegacy(){document.querySelectorAll('.nav button').forEach(b=>b.remove());}
