document.addEventListener('DOMContentLoaded',()=>{
 const d=document.getElementById('dashboard'); if(!d)return;
 d.innerHTML=`<div class="dash-hero"><div><div class="dash-kicker">ASSET INTEGRITY MANAGEMENT</div><h1>Asset Database</h1><p>Central monitoring dashboard untuk Static Equipment, Inspection dan Risk Based Inspection.</p></div><div class="hero-status"><span class="live-dot"></span><div><b>System Online</b><small>Database & services available</small></div></div></div>
 <div class="dash-welcome"><div><span class="eyebrow">OVERVIEW</span><h2>Operational Asset Overview</h2><p>Pantau kondisi database dan akses modul utama dari satu halaman.</p></div><div class="dash-date">Assessment Period <b>24 Months (1AP)</b></div></div>
 <div class="dash-kpis"><div class="dash-kpi"><div class="kpi-icon blue">▦</div><div><small>Total Asset</small><b id="dashTotalAsset">-</b><span>Static equipment terdaftar</span></div></div><div class="dash-kpi"><div class="kpi-icon teal">◫</div><div><small>Inspection Records</small><b id="dashInspection">-</b><span>Riwayat inspection</span></div></div><div class="dash-kpi"><div class="kpi-icon amber">◉</div><div><small>RBI Assessment</small><b id="dashRbi">-</b><span>Asset dengan assessment</span></div></div><div class="dash-kpi risk"><div class="kpi-icon red">!</div><div><small>High Risk</small><b id="dashHighRisk">-</b><span>Unsatisfactory + Critical</span></div></div></div>
 <div class="dash-section-title"><div><h2>Quick Access</h2><p>Modul utama Asset Database</p></div></div>
 <div class="dash-modules"><button class="dash-module" data-page="assets"><span class="module-icon blue">▦</span><span><b>Asset Register</b><small>Kelola dan telusuri seluruh static equipment berdasarkan Wilayah Kerja dan Location.</small></span><strong>→</strong></button><button class="dash-module" data-page="inspection"><span class="module-icon teal">◫</span><span><b>Inspection</b><small>Lihat inspection history dan data inspeksi yang tersedia.</small></span><strong>→</strong></button><button class="dash-module" data-page="rbi"><span class="module-icon amber">◉</span><span><b>RBI Assessment</b><small>Risk Matrix 1AP, Risk Summary dan Inspection Due Planning.</small></span><strong>→</strong></button><button class="dash-module" data-page="import"><span class="module-icon red">⇧</span><span><b>Import Data</b><small>Import asset, inspection dan RBI data secara bertahap.</small></span><strong>→</strong></button></div>
 <div class="dash-bottom-grid"><div class="panel dash-system"><div class="panel-title"><div><h2>System Status</h2><p>Status aplikasi dan konfigurasi utama.</p></div><span class="status good">Operational</span></div><div class="system-rows"><div><span>Database</span><b><i class="live-dot"></i> Online</b></div><div><span>Assessment Period</span><b>24 Months (1AP)</b></div><div><span>Current Role</span><b id="dashRole">Admin</b></div><div><span>Data Architecture</span><b>Regional JSON / Manifest</b></div></div></div><div class="panel dash-focus"><div class="panel-title"><div><h2>Next Focus</h2><p>Modul yang sedang disiapkan</p></div></div><div class="focus-item"><span class="focus-number">01</span><div><b>RBI Module</b><small>Risk Matrix, Diagram Risiko, Summary dan Due Planning.</small></div><button class="outline-btn small dashboard-link" data-page="rbi">Open</button></div><div class="focus-item"><span class="focus-number">02</span><div><b>Import Workflow</b><small>Upload → Validate → Preview → Commit.</small></div><button class="outline-btn small dashboard-link" data-page="import">Open</button></div></div></div>`;
 const nav=p=>document.querySelector('.nav-item[data-page="'+p+'"]')?.click();
 d.querySelectorAll('.dash-module,.dashboard-link').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.page)));
 fetch('data/manifest.json',{cache:'no-store'}).then(r=>r.json()).then(x=>{const n=id=>document.getElementById(id);if(n('dashTotalAsset'))n('dashTotalAsset').textContent=Number(x.totalAssets||0).toLocaleString('id-ID');if(n('dashInspection'))n('dashInspection').textContent=Number(x.totalInspections||0).toLocaleString('id-ID');if(n('dashRbi'))n('dashRbi').textContent=Number(x.totalRbi||0).toLocaleString('id-ID');const rc=x.riskCounts||{};const high=Object.entries(rc).filter(([k])=>['5D','5E','4E','3E'].includes(k)).reduce((s,[,v])=>s+Number(v||0),0);if(n('dashHighRisk'))n('dashHighRisk').textContent=high.toLocaleString('id-ID');}).catch(console.warn);
});