(()=>{
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
let data=[], enriched=[], ready=false;
const style=document.createElement('style');style.id='inspection-template-style';style.textContent=`
#inspection .inspection-page{background:#fff;border:1px solid #e0e7ef;border-radius:12px;padding:22px 20px;box-shadow:0 2px 10px rgba(20,45,70,.035)}
#inspection .inspection-head{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;margin-bottom:18px}.inspection-head h1{font-size:25px!important;margin:0 0 8px!important;color:#12263a}.inspection-head p{font-size:13px!important;color:#64778a!important;margin:0!important}.inspection-year-select{height:40px;min-width:150px;border:1px solid #cfdae5;border-radius:8px;padding:0 12px;background:#fff;color:#1266c9;font-size:13px;font-weight:700}
#inspection .inspection-years{display:grid;grid-template-columns:repeat(7,1fr);gap:10px;margin:18px 0}.inspection-year-card{height:104px;border:1px solid #d8e2ec;border-radius:10px;background:#f8fafc;text-align:left;padding:14px 16px;cursor:pointer;transition:.15s}.inspection-year-card:hover{border-color:#1c73df;transform:translateY(-1px)}.inspection-year-card.selected{border-color:#0874df;background:#eef6ff;box-shadow:inset 0 0 0 1px #0874df}.inspection-year-card b{display:block;font-size:25px;line-height:1;color:#1469cf;margin-bottom:8px}.inspection-year-card span{display:block;font-size:12px;font-weight:700;color:#23384d}.inspection-year-card small{display:block;font-size:11px;color:#65788a;margin-top:7px}
#inspection .inspection-filterbar{display:grid;grid-template-columns:190px 270px 1fr auto;gap:10px;align-items:center;padding:12px;background:#f6f9fc;border:1px solid #dfe7ef;border-radius:10px;margin:18px 0 20px}.inspection-filterbar select,.inspection-filterbar input{height:40px;width:100%;border:1px solid #cbd7e2;border-radius:7px;background:#fff;padding:0 12px;color:#17324d;font-size:13px}.inspection-filterbar input{outline:none}.inspection-count{font-size:12px;color:#66809a;white-space:nowrap}
#inspection .inspection-table-head{display:flex;align-items:center;justify-content:space-between;margin:0 0 10px}.inspection-table-head h2{font-size:18px;margin:0;color:#12263a}.inspection-badge{background:#edf5ff;color:#0867cf;border-radius:16px;padding:7px 11px;font-size:12px;font-weight:800}.inspection-table-wrap{overflow:auto;border:1px solid #e0e7ee;border-radius:8px}.inspection-table{width:100%;border-collapse:collapse;font-size:12px}.inspection-table th{background:#f6f8fb;color:#42566a;font-size:11px;font-weight:800;padding:12px 10px;text-align:left;border-bottom:1px solid #dfe6ed}.inspection-table td{padding:12px 10px;border-bottom:1px solid #e9eef3;color:#314557;vertical-align:top;white-space:nowrap}.inspection-table td:first-child{font-weight:800;color:#1469cf}.inspection-table tr:hover td{background:#fbfdff}.inspection-pager{display:flex;justify-content:space-between;align-items:center;padding:12px 2px 0;color:#667b8d;font-size:11px}.inspection-pager button{height:30px;border:1px solid #ccd8e3;background:#fff;border-radius:6px;padding:0 10px;color:#1568c9;cursor:pointer}.inspection-pager button:disabled{color:#9aa8b5;background:#f5f7f9;cursor:not-allowed}
@media(max-width:1100px){#inspection .inspection-years{grid-template-columns:repeat(4,1fr)}#inspection .inspection-filterbar{grid-template-columns:1fr 1fr}.inspection-count{grid-column:1/-1}}@media(max-width:700px){#inspection .inspection-head{display:block}.inspection-year-select{margin-top:12px}#inspection .inspection-years{grid-template-columns:repeat(2,1fr)}#inspection .inspection-filterbar{grid-template-columns:1fr}.inspection-count{grid-column:auto}}
`;
document.head.appendChild(style);
function yearOf(v){const m=String(v||'').match(/(?:19|20)\d{2}/);return m?m[0]:'Unknown'}
function dateFmt(v){const m=String(v||'').match(/(\d{4})[-\/]?(\d{2})[-\/]?(\d{2})/);return m?`${m[3]}/${m[2]}/${m[1]}`:String(v||'-')}
async function load(){if(ready)return;const r=await fetch('data/inspections.json',{cache:'no-store'});data=await r.json();const manifest=await (await fetch('data/manifest.json',{cache:'no-store'})).json();const idx=new Map();await Promise.all((manifest.regions||[]).map(async rg=>{try{const d=await (await fetch(`data/regions/${encodeURIComponent(rg.slug)}.json`,{cache:'no-store'})).json();(d.assets||[]).forEach(a=>idx.set(String(a.tag||'').trim(),{wilayahKerja:d.wilayahKerja||rg.name||'',location:a.area||''}))}catch(e){}}));enriched=data.map(x=>({...x,...(idx.get(String(x.tag||'').trim())||{})}));ready=true}
function render(){
 const root=document.getElementById('inspection');if(!root)return;
 const selected=document.getElementById('inspectionYearTemplate')?.value||'';
 let region=document.getElementById('inspectionRegionTemplate')?.value||'';
 let location=document.getElementById('inspectionLocationTemplate')?.value||'';
 const q=(document.getElementById('inspectionSearchTemplate')?.value||'').toLowerCase().trim();
 const yearData=selected?enriched.filter(x=>yearOf(x.date)===selected):enriched;
 const validRegions=[...new Set(yearData.map(x=>x.wilayahKerja).filter(Boolean))].sort();
 if(region&&!validRegions.includes(region))region='';
 const regionData=region?yearData.filter(x=>x.wilayahKerja===region):yearData;
 const availableLocations=[...new Set(regionData.map(x=>x.location).filter(Boolean))].sort();
 const validLocation=location&&availableLocations.includes(location)?location:'';
 const filtered=regionData.filter(x=>(!validLocation||x.location===validLocation)&&(!q||`${x.tag} ${x.finding||''} ${x.remarks||''}`.toLowerCase().includes(q)));
 const years=[...new Set(enriched.map(x=>yearOf(x.date)).filter(y=>y!=='Unknown'))].sort((a,b)=>+b-+a);
 const grouped={};enriched.forEach(x=>{const y=yearOf(x.date);if(y!=='Unknown')(grouped[y]??=[]).push(x)});
 const currentPage=Number(root.dataset.inspectionPage||1);const pageSize=50;const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize));const page=Math.min(currentPage,totalPages);root.dataset.inspectionPage=page;const rows=filtered.slice((page-1)*pageSize,page*pageSize);
 root.innerHTML=`<div class="inspection-page"><div class="inspection-head"><div><h1>Inspection History by Year</h1><p>Inspection report dikelompokkan berdasarkan tahun inspeksi. Data inspection dimuat hanya saat ini dibuka.</p></div><select class="inspection-year-select" id="inspectionYearTemplate"><option value="">All Years</option>${years.map(y=>`<option value="${y}" ${selected===y?'selected':''}>${y}</option>`).join('')}</select></div><div class="inspection-years">${years.map(y=>`<button class="inspection-year-card ${selected===y?'selected':''}" data-year="${y}"><b>${y}</b><span>${(grouped[y]?.length||0).toLocaleString('id-ID')} inspection</span><small>View report →</small></button>`).join('')}</div><div class="inspection-filterbar"><select id="inspectionRegionTemplate"><option value="">All Wilayah Kerja</option>${validRegions.map(v=>`<option value="${esc(v)}" ${region===v?'selected':''}>${esc(v)}</option>`).join('')}</select><select id="inspectionLocationTemplate" ${!region||!availableLocations.length?'disabled':''}><option value="">All Location</option>${availableLocations.map(v=>`<option value="${esc(v)}" ${validLocation===v?'selected':''}>${esc(v)}</option>`).join('')}</select><input id="inspectionSearchTemplate" value="${esc(q)}" placeholder="Search Tag No / Finding / Remarks"><span class="inspection-count">${filtered.length.toLocaleString('id-ID')} inspection</span></div><div class="inspection-table-head"><h2>Inspection ${selected||'All Years'}</h2><span class="inspection-badge">${filtered.length.toLocaleString('id-ID')} inspection</span></div><div class="inspection-table-wrap"><table class="inspection-table"><thead><tr><th>Tag No.</th><th>Wilayah Kerja</th><th>Location</th><th>Date</th><th>Method</th><th>Finding</th><th>Remarks</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.tag)}</td><td>${esc(x.wilayahKerja||'-')}</td><td>${esc(x.location||'-')}</td><td>${dateFmt(x.date)}</td><td>${esc(x.method||'-')}</td><td>${esc(x.finding||'-')}</td><td>${esc(x.remarks||'-')}</td></tr>`).join('')||'<tr><td colspan="7" style="text-align:center;padding:30px">Tidak ada data inspection.</td></tr>'}</tbody></table></div><div class="inspection-pager"><span>Showing ${(filtered.length?((page-1)*pageSize+1):0)} to ${Math.min(page*pageSize,filtered.length)} of ${filtered.length.toLocaleString('id-ID')} entries</span><div><button id="inspectionPrev" ${page<=1?'disabled':''}>‹</button> <span style="margin:0 8px">${page} / ${totalPages}</span><button id="inspectionNext" ${page>=totalPages?'disabled':''}>›</button></div></div></div>`;
 root.querySelectorAll('.inspection-year-card').forEach(b=>b.onclick=()=>{root.dataset.inspectionPage=1;root.querySelector('#inspectionYearTemplate').value=b.dataset.year;render()});
 root.querySelector('#inspectionYearTemplate').onchange=()=>{root.dataset.inspectionPage=1;render()};
 root.querySelector('#inspectionRegionTemplate').onchange=()=>{root.dataset.inspectionPage=1;render()};
 root.querySelector('#inspectionLocationTemplate').onchange=()=>{root.dataset.inspectionPage=1;render()};
 root.querySelector('#inspectionSearchTemplate').oninput=()=>{root.dataset.inspectionPage=1;render()};
 root.querySelector('#inspectionPrev').onclick=()=>{root.dataset.inspectionPage=page-1;render()};root.querySelector('#inspectionNext').onclick=()=>{root.dataset.inspectionPage=page+1;render()};
}
async function open(){try{await load();render()}catch(e){console.error(e)}}
function bind(){document.querySelectorAll('.nav-item[data-page="inspection"],.dashboard-link[data-page="inspection"]').forEach(b=>b.addEventListener('click',()=>setTimeout(open,0)));if(document.getElementById('inspection')?.classList.contains('active'))open()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();