let DB=null,regions={},allAssets=null,inspectionData=null,dueBuckets={},currentDue='2026',duePage=1;const $=id=>document.getElementById(id),PAGE=5,TODAY=new Date('2026-08-12T00:00:00');
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>Number(v||0).toLocaleString('id-ID');
function dt(v){const m=String(v||'').match(/(19|20)\d{2}-\d{2}-\d{2}/);return m?new Date(m[0]+'T00:00:00'):null}
function fd(v){const d=dt(v);return d?`${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()}`:(v||'-')}
const RM={5:{A:'U',B:'U',C:'U',D:'C',E:'C'},4:{A:'T',B:'T',C:'T',D:'T',E:'C'},3:{A:'A',B:'A',C:'T',D:'T',E:'C'},2:{A:'F',B:'A',C:'T',D:'T',E:'U'},1:{A:'F',B:'F',C:'T',D:'T',E:'T'}};
const C={F:'#08ad5a',A:'#86c744',T:'#ffe000',U:'#ffab00',C:'#f20b13',N:'#d7dce1'};
const names={F:'Favourable',A:'Acceptable',T:'Tolerable',U:'Unsatisfactory',C:'Critical',N:'No AP Detected'},order=['F','A','T','U','C','N'];
function cat(r){const m=String(r||'').toUpperCase().match(/^([1-5])([A-E])$/);return m?(RM[+m[1]]?.[m[2]]||'N'):'N'}
function counts(list){const x={};list.forEach(a=>{const r=String(a.risk1AP||a.risk||'').toUpperCase();x[r]=(x[r]||0)+1});return x}
function catCounts(raw){const x={F:0,A:0,T:0,U:0,C:0,N:0};Object.entries(raw||{}).forEach(([r,n])=>x[cat(r)]+=Number(n)||0);return x}
async function manifest(){if(DB)return DB;const r=await fetch('data/manifest.json',{cache:'no-store'});if(!r.ok)throw new Error('Manifest tidak dapat dimuat');DB=await r.json();return DB}
async function region(slug){if(regions[slug])return regions[slug];const r=await fetch(`data/regions/${encodeURIComponent(slug)}.json`,{cache:'no-store'});if(!r.ok)throw new Error(`Data wilayah ${slug} tidak dapat dimuat`);const d=await r.json();return regions[slug]=d.assets||[]}
async function assets(){if(allAssets)return allAssets;await manifest();allAssets=(await Promise.all((DB.regions||[]).map(r=>region(r.slug)))).flat();return allAssets}
function opts(){return '<option value="">All Wilayah Kerja</option>'+(DB.regions||[]).map(r=>`<option value="${esc(r.slug)}">${esc(r.name)}</option>`).join('')}
function matrix(id,raw){const el=$(id);if(!el)return;const rows=[5,4,3,2,1],cols=['A','B','C','D','E'];el.innerHTML=`<div class="matrix-wrap"><div class="matrix-y">Likelihood</div><div><div class="matrix-grid"><div></div>${cols.map(c=>`<div class="axis">${c}</div>`).join('')}${rows.map(r=>`<div class="axis">${r}</div>${cols.map(c=>{const k=r+c,g=RM[r][c],n=raw[k]||0;return `<div class="risk-cell" style="background:${C[g]}"><b>${fmt(n)}</b><small>${k}</small></div>`}).join('')}`).join('')}</div><div class="matrix-x">Consequence</div></div></div>`}
function chart(donutId,sumId,raw,total){const d=$(donutId),sEl=$(sumId);if(!d||!sEl)return;const cc=catCounts(raw),parts=[];let s=0;order.forEach(k=>{if(cc[k]&&total){const e=s+cc[k]/total*360;parts.push(`${C[k]} ${s}deg ${e}deg`);s=e}});d.innerHTML=`<div class="donut" style="background:conic-gradient(${parts.join(',')||'#d7dce1 0 360deg'})"><div><b>${fmt(total)}</b><span>Total Asset</span></div></div>`;sEl.innerHTML=`<div class="summary"><h4>RBI Risk Summary</h4><div class="summary-head"><span>Kategori</span><span>Jumlah</span><span>Persentase</span></div>${order.map(k=>`<div class="summary-row"><span><i style="background:${C[k]}"></i>${names[k]}</span><b>${fmt(cc[k])}</b><small>${total?((cc[k]/total)*100).toFixed(1):'0.0'}%</small></div>`).join('')}</div>`}
function renderRisk(matrixId,donutId,sumId,raw,total){matrix(matrixId,raw);chart(donutId,sumId,raw,total)}
function bindNav(){document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>page(b.dataset.page));const menu=$('menuToggle');if(menu)menu.onclick=()=>document.body.classList.toggle('sidebar-open');const theme=$('themeBtn');if(theme)theme.onclick=()=>document.body.classList.toggle('dark');const roleBtn=$('roleBtn'),roleMenu=$('roleMenu');if(roleBtn&&roleMenu){roleBtn.onclick=e=>{e.stopPropagation();roleMenu.classList.toggle('open')};roleMenu.querySelectorAll('button').forEach(b=>b.onclick=()=>{if($('roleName'))$('roleName').textContent=b.dataset.role;roleMenu.classList.remove('open');if($('dashRole'))$('dashRole').textContent=b.dataset.role});document.addEventListener('click',()=>roleMenu.classList.remove('open'))}const imp=$('importFile');if(imp)imp.onchange=()=>{if($('importFileName'))$('importFileName').textContent=imp.files[0]?`Selected: ${imp.files[0].name}`:''}}
function page(p){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===p));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===p));const m={dashboard:['Dashboard','Overview'],assets:['Asset Register','Database'],inspection:['Inspection','History'],rbi:['RBI','Assessment'],reports:['Report','Reports'],master:['Data Master','Master Data'],users:['User Management','Users & Roles'],import:['Import Data','Import'],settings:['Settings','Configuration']}[p]||['Dashboard',p];if($('crumbParent'))$('crumbParent').textContent=m[0];if($('crumbCurrent'))$('crumbCurrent').textContent=m[1];if(p==='assets')loadAssetPage();if(p==='inspection')loadInspectionPage();if(p==='rbi')loadRbiPage();window.scrollTo(0,0)}
async function loadDashboard(){await manifest();const set=(id,v)=>{if($(id))$(id).textContent=fmt(v)};set('dashTotalAsset',DB.totalAssets);set('dashInspection',DB.totalInspections);set('dashRbi',DB.totalRbi);const rc=DB.riskCounts||{};const high=Object.entries(rc).filter(([k])=>['5D','5E','4E','3E'].includes(k)).reduce((s,[,v])=>s+Number(v||0),0);set('dashHighRisk',high)}
async function loadAssetPage(){await manifest();const rg=$('assetRegion');if(!rg)return;if(!rg.options.length)rg.innerHTML=opts();if(rg.dataset.bound)return;rg.dataset.bound=1;rg.onchange=async()=>{const s=rg.value;if(!s){if($('assetTable'))$('assetTable').innerHTML='<div class="empty">Pilih Wilayah Kerja.</div>';return}window.assetList=await region(s);const locs=[...new Set(assetList.map(a=>a.area).filter(Boolean))].sort();if($('assetLocation')){$('assetLocation').disabled=false;$('assetLocation').innerHTML='<option value="">All Location</option>'+locs.map(x=>`<option>${esc(x)}</option>`).join('')}renderAssets()};if($('assetLocation'))$('assetLocation').onchange=renderAssets;if($('assetSearch'))$('assetSearch').oninput=renderAssets;if($('assetExport'))$('assetExport').onclick=()=>downloadCsv('asset-register.csv',window.assetList||[])}
function renderAssets(){const q=($('assetSearch')?.value||'').toLowerCase(),l=$('assetLocation')?.value||'',a=(window.assetList||[]).filter(x=>(!l||x.area===l)&&(!q||`${x.tag} ${x.name}`.toLowerCase().includes(q)));if(!$('assetTable'))return;$('assetTable').innerHTML=`<div class="table-scroll"><table><thead><tr><th>No</th><th>Tag Number</th><th>Equipment Name</th><th>Object Type</th><th>Location</th><th>Risk 1AP</th><th>Integrity Status</th><th>Remarks</th></tr></thead><tbody>${a.slice(0,50).map((x,i)=>`<tr><td>${i+1}</td><td class="link">${esc(x.tag)}</td><td>${esc(x.name||'-')}</td><td>${esc(x.objectType||'-')}</td><td>${esc(x.area||'-')}</td><td><span class="risk-tag">${esc(x.risk1AP||'-')}</span></td><td><span class="integrity ${String(x.integrityStatus||'').toLowerCase()}">${esc(x.integrityStatus||'-')}</span></td><td>${esc(x.remarks||'-')}</td></tr>`).join('')}</tbody></table></div><div class="pager"><span>${fmt(a.length)} asset</span></div>`}
async function loadInspectionPage(){if(inspectionData)return;inspectionData=await (await fetch('data/inspections.json',{cache:'no-store'})).json();const ys=[...new Set(inspectionData.map(x=>String(x.date||'').slice(0,4)).filter(y=>/^20\d{2}$/.test(y)))].sort().reverse();if($('inspectionYear'))$('inspectionYear').innerHTML='<option value="">All Years</option>'+ys.map(y=>`<option>${y}</option>`).join('');if($('inspectionYear'))$('inspectionYear').onchange=renderInspection;if($('inspectionSearch'))$('inspectionSearch').oninput=renderInspection;renderInspection()}
function renderInspection(){const y=$('inspectionYear')?.value||'',q=($('inspectionSearch')?.value||'').toLowerCase(),a=(inspectionData||[]).filter(x=>(!y||String(x.date).startsWith(y))&&(!q||String(x.tag).toLowerCase().includes(q)));if(!$('inspectionTable'))return;$('inspectionTable').innerHTML=`<div class="table-scroll"><table><thead><tr><th>No</th><th>Tag Number</th><th>Inspection Date</th><th>Method</th><th>Finding</th><th>Remarks</th></tr></thead><tbody>${a.slice(0,100).map((x,i)=>`<tr><td>${i+1}</td><td class="link">${esc(x.tag)}</td><td>${fd(x.date)}</td><td>${esc(x.method||'-')}</td><td>${esc(x.finding||'-')}</td><td>${esc(x.remarks||'-')}</td></tr>`).join('')}</tbody></table></div><div class="pager"><span>${fmt(a.length)} records</span></div>`}
async function buildDue(){const a=await assets(),b={'Overdue':[],'2026':[],'2027':[],'2028':[],'2029':[],'2030':[],'> 2030':[]};a.forEach(x=>{const d=dt(x.inspectionDueDate);if(!d)return;if(d<TODAY)b.Overdue.push(x);else if(d.getFullYear()<=2030)b[String(d.getFullYear())].push(x);else b['> 2030'].push(x)});return b}
function dueCards(){const el=$('dueCards');if(!el)return;el.innerHTML=Object.entries(dueBuckets).map(([k,v])=>`<button class="due-card ${k===currentDue?'selected':''}" data-y="${k}"><b>${k}</b><span>${fmt(v.length)} Asset</span></button>`).join('');el.querySelectorAll('.due-card').forEach(x=>x.onclick=()=>{currentDue=x.dataset.y;duePage=1;dueCards();dueTable()})}
function dueTable(){const el=$('dueTable');if(!el)return;let list=dueBuckets[currentDue]||[],q=($('dueSearch')?.value||'').toLowerCase();if(q)list=list.filter(a=>`${a.tag} ${a.name} ${a.wilayahKerja} ${a.area}`.toLowerCase().includes(q));if($('dueTitle'))$('dueTitle').textContent=`${currentDue} Inspection Due`;if($('dueCount'))$('dueCount').textContent=`${fmt(list.length)} Asset`;const start=(duePage-1)*PAGE,rows=list.slice(start,start+PAGE);el.innerHTML=`<div class="table-scroll"><table><thead><tr><th>No</th><th>Tag Number</th><th>Equipment Name</th><th>Wilayah Kerja</th><th>Location</th><th>Risk 1AP</th><th>Integrity Status</th><th>Last Inspection</th><th>Inspection Due Date</th><th>Action</th></tr></thead><tbody>${rows.map((a,i)=>`<tr><td>${start+i+1}</td><td class="link">${esc(a.tag)}</td><td>${esc(a.name||'-')}</td><td>${esc(a.wilayahKerja||'-')}</td><td>${esc(a.area||'-')}</td><td><span class="risk-tag">${esc(a.risk1AP||'-')}</span></td><td><span class="integrity ${String(a.integrityStatus||'').toLowerCase()}">${esc(a.integrityStatus||'-')}</span></td><td>${fd(a.lastInspectionDate)}</td><td>${fd(a.inspectionDueDate)}</td><td><button class="view-btn">◉</button></td></tr>`).join('')}</tbody></table></div>`}
async function loadRbiPage(){await manifest();const rg=$('rbiRegion');if(!rg)return;if(!rg.dataset.bound){rg.innerHTML=opts();rg.dataset.bound=1;rg.onchange=renderRbi;if($('rbiLocation'))$('rbiLocation').onchange=renderRbi;if($('rbiSearch'))$('rbiSearch').oninput=renderRbi;if($('rbiExport'))$('rbiExport').onclick=()=>downloadCsv('rbi-assessment.csv',window.rbiList||[]);if($('dueSearch'))$('dueSearch').oninput=dueTable}renderRisk('rbiMatrix','rbiDonut','rbiSummary',DB.riskCounts||{},DB.totalAssets||0);if($('rbiMatrixCount'))$('rbiMatrixCount').textContent=`${fmt(DB.totalAssets)} Asset`;if($('rbiDiagramCount'))$('rbiDiagramCount').textContent=`${fmt(DB.totalAssets)} Asset`;if(!Object.keys(dueBuckets).length){dueBuckets=await buildDue();dueCards();dueTable()}await renderRbi()}
async function renderRbi(){const s=$('rbiRegion')?.value||'',l=$('rbiLocation')?.value||'',q=($('rbiSearch')?.value||'').toLowerCase();let a=s?await region(s):await assets();if(s&&$('rbiLocation')){const locs=[...new Set(a.map(x=>x.area).filter(Boolean))].sort();$('rbiLocation').disabled=false;$('rbiLocation').innerHTML='<option value="">All Location</option>'+locs.map(x=>`<option>${esc(x)}</option>`).join('')}else if($('rbiLocation'))$('rbiLocation').disabled=true;a=a.filter(x=>(!l||x.area===l)&&(!q||`${x.tag} ${x.name}`.toLowerCase().includes(q)));window.rbiList=a;renderRisk('rbiMatrix','rbiDonut','rbiSummary',counts(a),a.length);if($('rbiMatrixCount'))$('rbiMatrixCount').textContent=`${fmt(a.length)} Asset`;if($('rbiDiagramCount'))$('rbiDiagramCount').textContent=`${fmt(a.length)} Asset`;if($('rbiTableCount'))$('rbiTableCount').textContent=`${fmt(a.length)} Asset`;if($('rbiTable'))$('rbiTable').innerHTML=`<div class="table-scroll"><table><thead><tr><th>No</th><th>Tag Number</th><th>Equipment Name</th><th>Wilayah Kerja</th><th>Location</th><th>Risk 1AP</th><th>Integrity Status</th><th>Last Inspection</th><th>Inspection Due Date</th></tr></thead><tbody>${a.slice(0,50).map((x,i)=>`<tr><td>${i+1}</td><td class="link">${esc(x.tag)}</td><td>${esc(x.name||'-')}</td><td>${esc(x.wilayahKerja||'-')}</td><td>${esc(x.area||'-')}</td><td><span class="risk-tag">${esc(x.risk1AP||'-')}</span></td><td><span class="integrity ${String(x.integrityStatus||'').toLowerCase()}">${esc(x.integrityStatus||'-')}</span></td><td>${fd(x.lastInspectionDate)}</td><td>${fd(x.inspectionDueDate)}</td></tr>`).join('')}</tbody></table></div>`}
function downloadCsv(name,list){if(!Array.isArray(list)||!list.length)return;const cols=Object.keys(list[0]);const csv=[cols.join(','),...list.map(x=>cols.map(k=>`"${String(x[k]??'').replace(/"/g,'""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
async function init(){try{await loadDashboard();bindNav()}catch(e){console.error(e);const d=document.querySelector('.content');if(d)d.innerHTML=`<div class="panel" style="color:#d00">Database belum tersedia: ${esc(e.message)}</div>`}}
document.addEventListener('DOMContentLoaded',init);