/* RBI direct mode: filters RBI data without requiring Asset Register selection. */
(() => {
  let allRbi = [], loaded = false;
  const escR = v => String(v ?? '').replace(/[&<>\"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const yearR = v => { const m=String(v??'').match(/(?:19|20)\d{2}/); return m?m[0]:''; };
  const dateR = v => { const m=String(v??'').match(/^(\d{4})-(\d{2})-(\d{2})/); if(!m)return String(v??'-')||'-'; const mo=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']; return `${m[3]}/${mo[Number(m[2])-1]||m[2]}/${m[1]}`; };
  const colors={Favourable:'#00b050',Acceptable:'#92d050',Tolerable:'#fff200',Unsatisfactory:'#ffc000',Critical:'#ff0000','No AP Detected':'#d9dde3'};
  const matrix={5:{A:'Unsatisfactory',B:'Unsatisfactory',C:'Unsatisfactory',D:'Critical',E:'Critical'},4:{A:'Tolerable',B:'Tolerable',C:'Tolerable',D:'Tolerable',E:'Critical'},3:{A:'Acceptable',B:'Acceptable',C:'Tolerable',D:'Tolerable',E:'Critical'},2:{A:'Favourable',B:'Acceptable',C:'Tolerable',D:'Tolerable',E:'Unsatisfactory'},1:{A:'Favourable',B:'Favourable',C:'Tolerable',D:'Tolerable',E:'Tolerable'}};
  const order=['Favourable','Acceptable','Tolerable','Unsatisfactory','Critical','No AP Detected'];

  async function loadAllRbi(){ if(loaded)return; const m=window.MANIFEST||{}, regions=Array.isArray(m.regions)?m.regions:[]; const chunks=await Promise.all(regions.map(async r=>{try{const res=await fetch(`data/regions/${encodeURIComponent(r.slug)}.json`,{cache:'no-store'});if(!res.ok)return[];const d=await res.json();return(Array.isArray(d.assets)?d.assets:[]).map(x=>({...x,wilayahKerja:String(d.wilayahKerja||r.name||''),location:String(x.area||'')}));}catch(_){return[];}})); allRbi=chunks.flat(); loaded=true; }
  function source(){const r=document.getElementById('rbiDirectRegion')?.value||'',l=document.getElementById('rbiDirectLocation')?.value||'';return allRbi.filter(x=>(!r||x.wilayahKerja===r)&&(!l||x.location===l));}
  function riskKey(x){const r=String(x.risk1AP||'').trim().toUpperCase();return /^[1-5][A-E]$/.test(r)?r:'Unknown';}
  function cat(r){const m=String(r||'').match(/^([1-5])([A-E])$/);return m?(matrix[Number(m[1])]?.[m[2]]||'No AP Detected'):'No AP Detected';}
  function renderRisk(list){const raw={};list.forEach(x=>{const k=riskKey(x);raw[k]=(raw[k]||0)+1;});const counts={};order.forEach(k=>counts[k]=0);Object.entries(raw).forEach(([k,n])=>counts[cat(k)]+=Number(n)||0);const riskEl=document.getElementById('rbiDirectMatrix'),sumEl=document.getElementById('rbiDirectSummary'),diaEl=document.getElementById('rbiDirectDiagram');if(!riskEl||!sumEl||!diaEl)return;
    const rows=[5,4,3,2,1],cols=['A','B','C','D','E'];riskEl.innerHTML=`<div class="risk-matrix-wrap"><div class="risk-matrix-ylabel">Likelihood</div><div class="risk-matrix-box"><div class="risk-matrix-grid"><div class="risk-corner"></div>${cols.map(c=>`<div class="risk-axis risk-axis-x">${c}</div>`).join('')}${rows.map(r=>`<div class="risk-axis risk-axis-y">${r}</div>${cols.map(c=>{const k=`${r}${c}`;return `<div class="risk-cell" style="background:${colors[matrix[r][c]]}" title="${k} — ${matrix[r][c]}"><span>${Number(raw[k]||0).toLocaleString('id-ID')}</span><small>${k}</small></div>`;}).join('')}`).join('')}</div><div class="risk-matrix-xlabel">Consequence</div></div></div>`;
    const total=order.reduce((s,k)=>s+counts[k],0);sumEl.innerHTML=`<div class="risk-summary-table-wrap"><table class="risk-summary-table"><thead><tr><th>Integrity Category</th><th>Jumlah</th><th>%</th></tr></thead><tbody>${order.map(k=>`<tr><td><span class="category-dot" style="background:${colors[k]}"></span>${k}</td><td><b>${counts[k].toLocaleString('id-ID')}</b></td><td>${total?((counts[k]/total)*100).toFixed(1):'0.0'}%</td></tr>`).join('')}<tr class="total-row"><td>TOTAL</td><td>${total.toLocaleString('id-ID')}</td><td>100%</td></tr></tbody></table></div>`;
    let start=0;const seg=order.filter(k=>counts[k]>0).map(k=>{const end=start+(counts[k]/Math.max(1,total))*360,s=`${colors[k]} ${start}deg ${end}deg`;start=end;return s;});diaEl.innerHTML=`<div class="risk-diagram"><div class="risk-donut" style="background:${seg.length?`conic-gradient(${seg.join(',')})`:`conic-gradient(#d9dde3 0 360deg)`}"><div class="risk-donut-center"><b>${total.toLocaleString('id-ID')}</b><span>Total</span></div></div><div class="risk-legend">${order.map(k=>`<div class="risk-legend-row"><span class="category-dot" style="background:${colors[k]}"></span><span>${k}</span><b>${counts[k].toLocaleString('id-ID')}</b><small>${total?((counts[k]/total)*100).toFixed(1):'0.0'}%</small></div>`).join('')}</div></div>`;
  }
  function populateRegions(){const s=document.getElementById('rbiDirectRegion');if(!s)return;const old=s.value,vals=[...new Set(allRbi.map(x=>x.wilayahKerja).filter(Boolean))].sort((a,b)=>a.localeCompare(b));s.innerHTML='<option value="">All Wilayah Kerja</option>'+vals.map(v=>`<option value="${escR(v)}">${escR(v)}</option>`).join('');if(vals.includes(old))s.value=old;updateLocations();}
  function updateLocations(){const r=document.getElementById('rbiDirectRegion'),l=document.getElementById('rbiDirectLocation');if(!r||!l)return;const old=l.value,vals=[...new Set(allRbi.filter(x=>!r.value||x.wilayahKerja===r.value).map(x=>x.location).filter(Boolean))].sort((a,b)=>a.localeCompare(b));l.innerHTML='<option value="">All Location</option>'+vals.map(v=>`<option value="${escR(v)}">${escR(v)}</option>`).join('');l.disabled=!r.value||!vals.length;if(vals.includes(old))l.value=old;else l.value='';}
  function dueSummary(){const host=document.getElementById('rbiDueSummary');if(!host)return;const list=source(),groups={};list.forEach(x=>{const y=yearR(x.inspectionDueDate);if(y)(groups[y] ||= []).push(x);});const years=Object.keys(groups).sort((a,b)=>Number(a)-Number(b));const cy=new Date().getFullYear(),overdue=list.filter(x=>{const y=yearR(x.inspectionDueDate);return y&&Number(y)<cy;});host.innerHTML=`<div class="rbi-due-cards">${overdue.length?`<button class="rbi-due-card overdue" data-due-year="OVERDUE"><b>Overdue</b><span>${overdue.length.toLocaleString('id-ID')} asset</span></button>`:''}${years.map(y=>`<button class="rbi-due-card" data-due-year="${y}"><b>${y}</b><span>${groups[y].length.toLocaleString('id-ID')} asset</span></button>`).join('')}</div>`;host.querySelectorAll('[data-due-year]').forEach(b=>b.addEventListener('click',()=>{document.getElementById('rbiDueYear').value=b.dataset.dueYear;renderDueTable();host.querySelectorAll('.rbi-due-card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');}));}
  function renderDueTable(){const host=document.getElementById('rbiDueTable');if(!host)return;const y=document.getElementById('rbiDueYear')?.value||'',cy=new Date().getFullYear(),list=source().filter(x=>!y||(y==='OVERDUE'?(yearR(x.inspectionDueDate)&&Number(yearR(x.inspectionDueDate))<cy):yearR(x.inspectionDueDate)===y));host.innerHTML=`<div class="report-heading"><h3>${y==='OVERDUE'?'Overdue':y?`Inspection Due ${y}`:'Inspection Due — All Years'}</h3><span class="badge">${list.length.toLocaleString('id-ID')} asset</span></div><div class="table-scroll"><table><thead><tr><th>Tag No.</th><th>Wilayah Kerja</th><th>Location</th><th>Risk 1AP</th><th>Integrity Status</th><th>Inspection Due Date</th></tr></thead><tbody>${list.slice(0,500).map(x=>`<tr><td><b>${escR(x.tag)}</b></td><td>${escR(x.wilayahKerja||'-')}</td><td>${escR(x.location||'-')}</td><td>${escR(x.risk1AP||'No AP Detected')}</td><td>${escR(x.integrityStatus||'-')}</td><td>${escR(dateR(x.inspectionDueDate))}</td></tr>`).join('')||'<tr><td colspan="6">Tidak ada asset sesuai filter.</td></tr>'}</tbody></table></div>`;}
  function renderAll(){const list=source();renderRisk(list);dueSummary();renderDueTable();const b=document.getElementById('rbiDirectCount');if(b)b.textContent=`${list.length.toLocaleString('id-ID')} asset`;}
  function buildUi(){const section=document.getElementById('rbi');if(!section||document.getElementById('rbiDirectUi'))return;const panel=section.querySelector('.panel');panel.innerHTML=`<div class="section-head"><h2>RBI Assessment</h2><span id="rbiDirectCount" class="badge">0 asset</span></div><div id="rbiDirectUi"><div class="rbi-direct-filters"><select id="rbiDirectRegion"><option>Loading...</option></select><select id="rbiDirectLocation" disabled><option>All Location</option></select></div><div class="rbi-direct-section"><div class="section-head"><h3>RBI Risk Matrix 1AP</h3><span class="badge">Risk 1AP</span></div><div id="rbiDirectMatrix"></div><div id="rbiDirectSummary"></div><div id="rbiDirectDiagram"></div></div><div class="rbi-direct-section"><div class="section-head"><h3>Inspection Due Planning</h3><select id="rbiDueYear"><option value="">All Years</option></select></div><div id="rbiDueSummary"></div><div id="rbiDueTable"></div></div></div>`;document.getElementById('rbiDirectRegion').addEventListener('change',()=>{updateLocations();renderAll();});document.getElementById('rbiDirectLocation').addEventListener('change',renderAll);document.getElementById('rbiDueYear').addEventListener('change',renderDueTable);}
  async function init(){buildUi();await loadAllRbi();populateRegions();renderAll();}
  window.initDirectRbi=init;document.addEventListener('click',e=>{const nav=e.target.closest('.nav button[data-page="rbi"]');if(nav)setTimeout(()=>init(),0);},true);
  const st=document.createElement('style');st.textContent=`.rbi-direct-filters{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:14px 0;padding:12px;background:#f7f9fc;border:1px solid #e2e8f0;border-radius:10px}.rbi-direct-filters select{padding:9px 11px;border:1px solid #cbd5e1;border-radius:7px;background:#fff;min-width:220px}.rbi-direct-filters select:disabled{background:#f1f5f9}.rbi-direct-section{margin-top:18px;padding-top:16px;border-top:1px solid #e2e8f0}.rbi-due-cards{display:flex;gap:10px;flex-wrap:wrap;margin:12px 0}.rbi-due-card{min-width:125px;padding:14px;border:1px solid #d8dee8;border-radius:10px;background:#fff;cursor:pointer;text-align:left}.rbi-due-card b,.rbi-due-card span{display:block}.rbi-due-card span{margin-top:5px;font-size:12px;color:#64748b}.rbi-due-card.selected{outline:2px solid #17324d}.rbi-due-card.overdue{border-color:#dc2626}.table-scroll{overflow:auto}.rbi-direct-section table{width:100%;border-collapse:collapse}.rbi-direct-section th,.rbi-direct-section td{padding:9px;border-bottom:1px solid #e5e7eb;text-align:left;white-space:nowrap}`;document.head.appendChild(st);
})();